### ISSUE TITLE
crash when joining or creating world | fabric 1.20.1

### ISSUE THREAD

**Issue by Surpos0** [Aeroshide/SyncedAdvancements#2]
crash report:
[crash-2023-11-14_22.19.52-client.txt](https://github.com/Aeroshide/SyncedAdvancements/files/13357043/crash-2023-11-14_22.19.52-client.txt)

**Comment by Aeroshide** [comment]
I put the wrong file on the 1.20.1 download, fixed it too couple weeks ago, so yeah try to redownload :)
